---
cloud_service_group: ComputeEngine
cloud_service_type: Disk
name: Count by Project
query:
  aggregate:
    - group:
        keys:
          - name: name
            key: account
        fields:
          - name: value
            operator: count
options:
  chart_type: DONUT