---
cloud_service_group: ComputeEngine
cloud_service_type: Disk
name: Total Count
query:
  aggregate:
    - group:
        fields:
          - name: value
            operator: count
options:
  value_options:
    key: value
    options:
      default: 0